// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        int64
	Code      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	ID        int64
	Code      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Token struct {
	Hash      []byte
	UserID    int64
	Expiry    pgtype.Timestamptz
	Scope     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              int64
	FullName        string
	Username        string
	Email           string
	PasswordHash    []byte
	ProfileImageUrl pgtype.Text
	Activated       bool
	LastLoginAt     pgtype.Timestamptz
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
